apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: u0mn5zp15-go 
  janus-idp.io/tekton: u0mn5zp15-go
  backstage.io/kubernetes-id: u0mn5zp15-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u0mn5zp15-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml