apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: u0mn5zp15-go-gitops
  description: This is GitOps manifest for u0mn5zp15-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=u0mn5zp15-go
    backstage.io/kubernetes-id: u0mn5zp15-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: u0mn5zp15-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:u0mn5zp15-go
